# name: Deploy to GitHub Pages

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           registry: https://index.docker.io/v1/
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

#       - name: Build and push Docker images
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: |
#             nikitaradzkov/backend:${{ github.sha }}
#             nikitaradzkov/frontend:${{ github.sha }}
#           platforms: linux/amd64

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.DEPLOY_TOKEN }}
#           publish_dir: ./client/build

#       - name: Deploy Spring Boot app
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.DEPLOY_TOKEN }}
#           publish_dir: ./api/src/main/resources/static
